name: Docker build
on: [ push, pull_request ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build (and do not push)
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        load: true
        #push: false
        #tags: user/app:latest
